gpu: "0"
multi_gpu: null

model_name: FlowNet3D
#model_name: RecurrentPoseCostVolume

full: True

arch: PointConv
last_relu: False
allow_less_points: False

# general args
batch_size: 16
epochs: 800
learning_rate: 0.001
loss_function: l2_loss
allow_self_supervised: False
allow_augmentation: False
sample_mode: FPS

optimizer: Adam
pretrain:  null
#pretrain: /model/1015323606/weekly_supervised_rigid_scene_flow/our_pretrain/FlyingThings3D/pointpwc_3scales/PointPWC_3scales_245_0.0502.pth
#pretrain: /model/1015323606/PointPWC_pretrain/FlowNet3D/FlowNet3D_712_0.0864.pth
#pretrain: /model/1015323606/PointPWC_pretrain/RecurrentPoseCostVolume/RecurrentPoseCostVolume_015_0.1279.pth
#pretrain: /model/1015323606/PointPWC_pretrain/PointConv_726_0.0463.pth
continue_pretrain: False


weight_decay: 0.0001

dim: 3
num_points: 8192

DEVICE: cuda

evaluate: False

dataset: FlyingThings3DSubset
data_root: /data/1015323606/FlyingThing3D_subset
data_process:
  DEPTH_THRESHOLD: 35.
  NO_CORR: True

# data augmentation
aug_together:
  degree_range: 0.1745329252
  shift_range: 1.
  scale_low: 0.95
  scale_high: 1.05
  jitter_sigma: 0.01
  jitter_clip: 0.00

aug_pc2:
  degree_range: 0.
  shift_range: 0.3
  jitter_sigma: 0.01
  jitter_clip: 0.00

# miscalleneous
workers: 16








